#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target=$1
readonly world_name=$2
readonly private_repo=$3

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

aviator -f "$basedir"/aviator.yml

fly --target "$target" \
  set-pipeline \
    --config "$PIPELINE_YML" \
    --pipeline "$world_name" \
    --var cluster-name="$world_name" \
    --var dockerhub-user=eiriniuser \
    --var dockerhub-password="$(pass eirini/docker-hub)" \
    --var eirini-release-private-key="$(pass eirini/github/eirini-release/ssh-key)" \
    --load-vars-from "$private_repo/concourse/common.yml" \
