#@data/values
---
slack:
  webhook:
dockerhub:
  username:
  password:
private_keys:
  eirinici:
gcp:
  service_account_json:
  zone: europe-west1-b
  region: europe-west1
  worker_count: 3
postfacto:
  mysql:
    address:
    password:
pairup:
  firebase_conf:
