#@ load("@ytt:data", "data")

#@ load("@ci:notifications.lib.yml", "notify_slack")
#@ load("@ci:resources.lib.yml", "resources")
#@ load("@ci:clusters.lib.yml", "clusters")
#@ load("@ci:egg.lib.yml", "egg")
#@ load("@ci:common.lib.yml", "git_commit")

jobs:
- name: deploy-postfacto
  on_failure: #@ notify_slack()
  plan:
  - in_parallel:
    - get: postfacto
      trigger: true
    - get: eirini-private-config
    - get: ci-resources
  - task: download-kubeconfig
    config: #@ clusters.download_kubeconfig("cf4k8s4a8e")
  - task: helm-install-redis
    config: #@ egg.helm_install_redis()
  - task: get-credentials
    config: #@ egg.get_redis_credentials()
  - task: deploy
    config: #@ egg.deploy_postfacto()
  serial: true

- name: deploy-jefe
  on_failure: #@ notify_slack()
  plan:
  - in_parallel:
    - get: docker-jefe
      passed:
      - build-jefe
      trigger: true
    - get: eirini-private-config
  - task: deploy
    config: #@ egg.deploy_jefe()
  serial: true

- name: deploy-eirinidotcf
  on_failure: #@ notify_slack()
  plan:
  - in_parallel:
    - get: ci-resources
    - get: eirinidotcf
      trigger: true
    - get: eirini-private-config
  - task: download-kubeconfig
    config: #@ clusters.download_kubeconfig("cf4k8s4a8e")
  - task: deploy-web
    config: #@ egg.deploy_eirinidotcf()
  serial: true

- name: unclaim-clusters
  on_failure: #@ notify_slack()
  plan:
  - get: every-morning
    trigger: true
  - task: unclaim
    config: #@ egg.unclaim_clusters()

- name: bump-eirinidotcf-dependencies
  on_failure: #@ notify_slack()
  plan:
  - get: every-week
    trigger: true
  - get: eirinidotcf
  - task: bump-eirinidotcf-dependencies
    config: #@ egg.bump_eirinidotcf_dependencies("eirinidotcf", "eirinidotcf-updated")
  - task: commit-bump
    config: #@ git_commit("eirinidotcf-updated", "eirinidotcf-committed", "Bump yarn packages", "web")
  - put: eirinidotcf
    params:
      repository: eirinidotcf-committed
  serial: true

- name: build-jefe
  plan:
  - get: jefe
    trigger: true
  - put: docker-jefe
    params:
      build: jefe
  serial: true

- name: deploy-pairup
  on_failure: #@ notify_slack()
  plan:
  - in_parallel:
    - get: ci-resources
    - get: pairup
      trigger: true
    - get: eirini-private-config
  - task: download-kubeconfig
    config: #@ clusters.download_kubeconfig("cf4k8s4a8e")
  - task: deploy-web
    config: #@ egg.deploy_pairup()
  serial: true

resource_types:
- #@ resources.registry_image_type("slack-notification", "cfcommunity/slack-notification-resource")

resources:
- #@ resources.slack()
- #@ resources.git("ci-resources", "cloudfoundry-incubator/eirini-ci")
- #@ resources.git("eirini-private-config", "cloudfoundry/eirini-private-config", "master", data.values.private_keys.eirinici)
- #@ resources.github_release("postfacto", "pivotal", "postfacto", "package.zip", "12h0m0s")
- #@ resources.git("jefe", "eirini-forks/jefe")
- #@ resources.git("eirinidotcf", "eirini-forks/eirinidotcf", "master", data.values.private_keys.eirinici)
- #@ resources.git("pairup", "eirini-forks/pairup")
- #@ resources.docker_image("docker-jefe", "eirini/jefe")
- icon: alarm
  name: every-morning
  source:
    start: 5:00 AM
    stop: 6:00 AM
  type: time
- icon: alarm
  name: every-week
  source:
    days:
    - Saturday
    start: 5:00 AM
    stop: 6:00 AM
  type: time
