#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly target="${1:-eirini}"

basedir="$(cd "$(dirname "$0")" && pwd)"
pushd "$basedir"
{
  aviator
}
popd

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline egg \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var mysql-password="$(pass show eirini/mysql-admin-password)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var jefe-client-id="$(pass eirini/jefe/client-id)" \
  --var jefe-client-secret="$(pass eirini/jefe/client-secret)" \
  --var jefe-dbuser-pass="$(pass eirini/jefe/dbuser-pass)" \
  --var jefe-admin-pass="$(pass eirini/jefe/admin-pass)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
