#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

pipeline_yml=$(mktemp)
readonly pipeline_yml
# shellcheck disable=SC2064
trap "rm $pipeline_yml" EXIT

target="${1:-eirini}"
readonly target

if ! fly -t "$target" status &>/dev/null; then
  fly -t "$target" login
fi

# We want this script to exit with error if pass or gcloud fails rather than
# silently interpolating an empty string into the pipeline vars!
#
# Assigning the subshell stdout to a variable preserves the expected semantics
# of errexit, as these assignments are "simple commands" rather than
# substitutions.
#
# This is a giant gotcha with shell scripts!
# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01

slack_webhook=$(pass eirini/ci/slack-webhook)
dockerhub_password=$(pass eirini/docker-hub)
private_keys_eirinici=$(pass eirini/github/eirinici/ssh-key)
private_keys_eirini_private_config=$(pass eirini/github/private-config/ssh-key)
gcp_service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)
postfacto_mysql_address=$(gcloud --project cff-eirini-peace-pods sql instances describe postfacto-cf4k8s4a8e --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')
postfacto_mysql_password=$(pass show eirini/postfacto-cf4k8s4a8e/mysql-admin-password)
jefe_github_oauth_client_id=$(pass eirini/jefe/client-id)
jefe_github_oauth_client_secret=$(pass eirini/jefe/client-secret)
jefe_db_password=$(pass eirini/jefe/dbuser-pass)
jefe_db_address=$(gcloud --project cff-eirini-peace-pods sql instances describe jefe-db --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')
jefe_admin_password=$(pass eirini/jefe/admin-pass)
pairup_firebase_conf=$(pass eirini/pairup/conf.js)

ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
  --data-value="slack.webhook=$slack_webhook" \
  --data-value="dockerhub.username=eiriniuser" \
  --data-value="dockerhub.password=$dockerhub_password" \
  --data-value="private_keys.eirinici=$private_keys_eirinici" \
  --data-value="private_keys.eirini_private_config=$private_keys_eirini_private_config" \
  --data-value="gcp.service_account_json=$gcp_service_account_json" \
  --data-value="postfacto.mysql.address=$postfacto_mysql_address" \
  --data-value="postfacto.mysql.password=$postfacto_mysql_password" \
  --data-value="jefe.github_oauth.client_id=$jefe_github_oauth_client_id" \
  --data-value="jefe.github_oauth.client_secret=$jefe_github_oauth_client_secret" \
  --data-value="jefe.db.password=$jefe_db_password" \
  --data-value="jefe.db.address=$jefe_db_address" \
  --data-value="jefe.admin_password=$jefe_admin_password" \
  --data-value="pairup.firebase_conf=$pairup_firebase_conf" \
  >"$pipeline_yml"

noColor=
if ! [ -t 1 ]; then
  noColor=--no-color
fi

fly --target "$target" \
  set-pipeline \
  "$noColor" \
  --config "$pipeline_yml" \
  --pipeline egg
