#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly target="${1:-eirini}"

basedir="$(cd "$(dirname "$0")" && pwd)"
pushd "$basedir"
{
  aviator
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi
jefe_db_ip_address="$(gcloud sql instances describe jefe-db --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')"

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline egg \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-zone="europe-west1-b" \
  --var gcp-region="europe-west1" \
  --var mysql-password="$(pass show eirini/mysql-admin-password)" \
  --var jefe-db-ip-address="$jefe_db_ip_address" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var eirinidotcf-private-key="$(pass eirini/github/eirinidotcf/ssh-key)" \
  --var jefe-client-id="$(pass eirini/jefe/client-id)" \
  --var jefe-client-secret="$(pass eirini/jefe/client-secret)" \
  --var jefe-dbuser-pass="$(pass eirini/jefe/dbuser-pass)" \
  --var jefe-admin-pass="$(pass eirini/jefe/admin-pass)" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
