#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
readonly target="${1:-eirini}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"

pushd "$basedir"
{
  aviator
}
popd

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline eirinifs \
  --var eirinifs-private-key="$(pass eirini/github/eirinifs/ssh-key)" \
  --var eirini-release-private-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var ci-resources-branch="master" \
  --var eirinifs-branch="master" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var eirini-release-branch="develop" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"

fly --target "$target" \
  expose-pipeline \
  --pipeline eirinifs
