#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target="${1:-eirini}"
readonly world_name=cf4k8s4a8e

pushd "$basedir"
{
  aviator
}
popd

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "acceptance" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var ci-resources-branch="master" \
  --var eirini-release-branch="master" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var eirini-staging-repo-key="$(pass eirini/github/eirini-staging/ssh-key)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-region="europe-west1" \
  --var gcp-zone="europe-west1-b" \
  --var world-name="$world_name" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
