#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly target="${1:-eirini}"

basedir="$(cd "$(dirname "$0")" && pwd)"
pushd "$basedir"
{
  aviator
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline egg-cf4k8s \
  --var gcp-region="europe-west1" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-zone="europe-west1-b" \
  --var mysql-address="$(gcloud --project cff-eirini-peace-pods sql instances describe postfacto-cf4k8s4a8e --format="value(ipAddresses[0].ipAddress)")" \
  --var mysql-password="$(pass show eirini/postfacto-cf4k8s4a8e/mysql-admin-password)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var jefe-client-id="$(pass eirini/jefe/client-id)" \
  --var jefe-client-secret="$(pass eirini/jefe/client-secret)" \
  --var jefe-dbuser-pass="$(pass eirini/jefe/dbuser-pass)" \
  --var jefe-admin-pass="$(pass eirini/jefe/admin-pass)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)" \
  --var admin-user="$(pass eirini/postfacto-cf4k8s4a8e/admin-user)" \
  --var admin-password="$(pass eirini/postfacto-cf4k8s4a8e/admin-password)"
