#!/bin/bash

set -e

readonly ALIAS="$1"
readonly PIPELINE_NAME=$(echo "$2" | awk '{print tolower($0)}')
readonly PRIVATE_REPO="$3"
readonly BOSH_DEPLOYMENT="${4?Path to bosh deployment repository is required}"
export ONE_CLICK="$5"
readonly USE_EIRINI_RELEASE="$6"
readonly PIPELINE_CONFIG_FILE="pipeline.yml"

help(){
  cat << EOF
  $ ./set-pipeline <CONCOURSE_TARGET> <PIPELINE_NAME> <PRIVATE_REPO> <BOSH_DEPLOYMENT> <ONE_CLICK_PIPELINE> <USE_EIRINI_RELEASE>
EOF
  exit 1
}

set-pipeline(){
  local env_file="$1"
  local use_eirini_release="$2"

  shift 2
  fly --target "$ALIAS" set-pipeline \
    --pipeline "$PIPELINE_NAME" \
    --config "$PIPELINE_CONFIG_FILE" \
    --var "kube_conf=$(kubectl config view --flatten)" \
    --var bosh-manifest="$(sed -e 's/((/_(_(/g' <(bin/create-director-manifest.sh "$PIPELINE_NAME" "$BOSH_DEPLOYMENT" "$ONE_CLICK" ) )" \
    --load-vars-from "$PRIVATE_REPO/concourse/common.yml" \
    --load-vars-from "$env_file" \
    --var use_eirini_release="$use_eirini_release" \
    --var docker_hub_password="$(pass eirini/docker-hub)" \
    --var world_name="$PIPELINE_NAME" \
    --var sl_vm_domain="softlayer.com" \
    --var bosh_lite_name="$PIPELINE_NAME" \
    --var cc_ng_key="$(pass eirini/github/mnitchev/cloud_controller_ng/ssh-key)" \
    --var capi-key="$(pass eirini/github/capi-release/ssh-key)" \
    --var eirini-release_repo_key="$(pass eirini/github/eirini-release/ssh-key)" \
    "$@"
}

set-ci-pipeline(){
  local repo_key_var="eirini_repo_key=$(pass eirini/github/eirini/ssh-key)"
  set-pipeline "env/eirini-ci.yml" true "--var" "$repo_key_var"
}

main(){
  if [ "$1" = "help" ]; then
    help
  fi

  if [ "$PIPELINE_NAME" = "eirini-ci" ]; then
    aviator -f aviator-ci.yml
    set-ci-pipeline
    exit 0
  fi

  if [ "$USE_EIRINI_RELEASE" = true ]; then
    aviator -f aviator.yml
    set-pipeline custom.yml "$USE_EIRINI_RELEASE"
    exit 0
  fi

  aviator -f aviator-helm.yml
  set-pipeline custom.yml "$USE_EIRINI_RELEASE"
}

main "$@"
