jobs:
- name: publish-release
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: ci-resources
  - get: state
    resource: cluster-state
    passed:
    - smoke-tests-cf4k8s4a8e
  - get: eirini-release
    passed:
    - smoke-tests-cf4k8s4a8e
  - get: eirini-release-version
  - task: create-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ibmcloud
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      inputs:
      - name: ci-resources
      - name: state
      - name: eirini-release
      - name: eirini-release-version
      outputs:
      - name: release-output
      - name: release-output-yaml
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/create-release.sh" ))
  - get: eirini
  - put: eirini-github-release
    params:
      globs:
      - release-output/eirini*.tgz
      name: eirini-release-version/version
      tag: eirini-release-version/version
      tag_prefix: v
  - task: checkout-eirini-sha
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eirini/ci
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
      inputs:
      - name: eirini-release
      - name: eirini
      - name: ci-resources
      outputs:
      - name: eirini-stable
      run:
        path: /usr/bin/env
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/checkout-sha-by-image.sh" ))
    privileged: true
  - put: eirini
    params:
      only_tag: true
      repository: eirini-stable
      tag: eirini-release-version/version
