jobs:
- name: run-tests
  public: true
  plan:
  - in_parallel:
      steps:
      - get: cluster-((world-name))-staging-event-created
        passed:
        - create-cluster-((world-name))
        trigger: true
      - get: eirini
        trigger: true
      - get: eirini-release
      - get: golang-lint
        params:
          skip_download: true
        trigger: true
      - get: ci-resources
  - in_parallel:
      steps:
      - task: run-unit-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: eirini/ci
              username: (( grab config.dockerhub.user ))
              password: (( grab config.dockerhub.password ))
          inputs:
          - name: eirini
          run:
            path: /usr/bin/env
            args:
            - bash
            - -c
            - (( file "../../inline-tasks/run-unit-tests.sh" ))
      - task: run-static-checks
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golangci/golangci-lint
              username: (( grab config.dockerhub.user ))
              password: (( grab config.dockerhub.password ))
              tag: latest
          inputs:
          - name: eirini
          run:
            path: /usr/bin/env
            args:
            - bash
            - -c
            - (( file "../../inline-tasks/run-static-checks.sh" ))
  on_failure: (( grab slack-notification.on_failure ))
