jobs:
- name: (( concat "smoke-tests-" config.cluster.name ))
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: cf-for-k8s-github-release
    params:
      include_source_tarball: true
    passed:
    - (( concat "deploy-cf-for-k8s-" config.cluster.name ))
    trigger: true
  - get: cluster-state
    passed:
    - (( concat "deploy-cf-for-k8s-" config.cluster.name ))
  - get: eirini-release
    passed:
    - (( concat "deploy-cf-for-k8s-" config.cluster.name ))
    trigger: true
  - task: get-smoke-tests-variables
    config:
      container_limits: {}
      image_resource:
        source:
          repository: eirini/ci
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
        type: docker-image
      inputs:
      - name: cluster-state
      outputs:
      - name: smoke-tests-env-vars
      platform: linux
      params:
        CLUSTER_NAME: (( grab config.cluster.name ))
      run:
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/get-smoke-tests-variables.sh" ))
        path: /usr/bin/env
  - task: run-smoke-tests
    config:
      container_limits: {}
      image_resource:
        source:
          repository: relintdockerhubpushbot/cf-for-k8s-ci
          username: (( grab config.dockerhub.user ))
          password: (( grab config.dockerhub.password ))
        type: docker-image
      inputs:
      - name: cf-for-k8s-github-release
      - name: smoke-tests-env-vars
      params:
        SMOKE_TEST_SKIP_SSL: "true"
        SMOKE_TEST_USERNAME: admin
      platform: linux
      run:
        args:
        - bash
        - -c
        - (( file "../../inline-tasks/run-smoke-tests.sh" ))
        path: /usr/bin/env
  public: true
  serial_groups:
  - (( grab config.cluster.name ))
