jobs:
- name: update-ci-image
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: golang-image
    trigger: true
  - get: ci-image-source
    trigger: true
  - put: ci-image
    get_params:
      skip_download: true
    params:
      build: ci-image-source/images/ci

- name: update-telepresence-image
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: telepresence-image-source
    trigger: true
  - put: telepresence-image
    get_params:
      skip_download: true
    params:
      build: telepresence-image-source/images/telepresence

- name: update-gcloud-image
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: golang-image
    trigger: true
  - get: gcloud-image-source
    trigger: true
  - put: gcloud-image
    get_params:
      skip_download: true
    params:
      build: gcloud-image-source/images/gcloud

- name: update-capi-tests-image
  on_failure: (( grab slack-notification.on_failure ))
  plan:
  - get: capi-ruby-units-image
    trigger: true
  - get: capi-tests-image-source
    trigger: true
  - put: capi-tests-image
    get_params:
      skip_download: true
    params:
      build: capi-tests-image-source/images/capi-tests
