#@data/values
---
slack:
  webhook:
dockerhub:
  username:
  password:
gcp:
  service_account_json:
  zone: europe-west1-b
  region: europe-west1
  worker_count:
wiremock_keystore_pass:
private_keys:
  eirini:
  eirini_release:
  eirini_private_config:
components:
  - api
  - eirini-controller
  - event-reporter
  - instance-index-env-injector
  - migration
  - resource-validator
  - task-reporter
repo_branches:
  eirini:
  eirini_ci:
