#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

pipeline_yml=$(mktemp)
readonly pipeline_yml
# shellcheck disable=SC2064
trap "rm $pipeline_yml" EXIT

target="${1:-eirini}"
readonly target

worker_count=${2:-"3"}
readonly worker_count

working_branch=${3:-"master"}
readonly working_branch

ci_branch=${4:-"master"}
readonly ci_branch

if ! fly -t "$target" status &>/dev/null; then
  fly -t "$target" login
fi

eirini_release_private_key=$(pass eirini/github/eirini-release/ssh-key)
ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
  --data-value="dockerhub.username=eiriniuser" \
  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
  --data-value="private_keys.eirini=$(pass eirini/github/eirini/ssh-key)" \
  --data-value="private_keys.eirini_release=$eirini_release_private_key" \
  --data-value="private_keys.eirini_private_config=$(pass eirini/github/private-config/ssh-key)" \
  --data-value="gcp.service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --data-value="wiremock_keystore_pass=$(pass eirini/ci/wiremock-keystore-password)" \
  --data-value="gcp.worker_count=$worker_count" \
  --data-value="repo_branches.eirini=$working_branch" \
  --data-value="repo_branches.eirini_ci=$ci_branch" \
  >"$pipeline_yml"

fly --target "$target" \
  set-pipeline \
  --config "$pipeline_yml" \
  --pipeline ci
