groups:
- (( prepend ))
- name: eirini-ci
  jobs:
  - run-unit-tests
  - run-static-checks
  - create-docker-images
  - deploy-scf-uaa
  - deploy-scf-eirini
  - deploy-oratos
  - run-smoke-tests
  - run-cats-subset

jobs:
- name: run-unit-tests
  plan:
  - get: ((cluster-name))-event-ready
    trigger: true
    passed:
    - check-cluster-readiness
  - get: eirini-source
    trigger: true
  - get: ci-resources
  - task: run-tests
    file: ci-resources/tasks/run-unit-tests/task.yml
- name: run-static-checks
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - run-unit-tests
  - get: ((cluster-name))-event-ready
    trigger: true
    passed:
    - run-unit-tests
  - get: ci-resources
  - task: run-static-checks
    file: ci-resources/tasks/run-static-checks/task.yml
- name: create-docker-images
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - run-static-checks
  - get: ((cluster-name))-event-ready
    trigger: true
    passed:
    - run-static-checks
  - get: ci-resources
  - get: eirini-release
  - get: scf-resources
  - get: ((cluster-name))-deployment-version
    params:
      bump: major
  - task: create images
    privileged: true
    params:
      DOCKER_HUB_USER: ((dockerhub-user))
      DOCKER_HUB_PASSWORD: ((dockerhub-password))
      TAG: ((cluster-name))
    file: ci-resources/tasks/create-docker-images/task.yml
  - put: ((cluster-name))-deployment-version
    params:
      file: ((cluster-name))-deployment-version/number
- name: deploy-scf-uaa
  plan:
  - get: ((cluster-name))-event-ready
    trigger: true
    passed:
    - create-docker-images
  - get: scf-uaa-resources
    trigger: true
  - get: ci-resources
  - get: eirini-release
  - get: state
  - get: ((cluster-name))-event-uaa-ready
    params:
      bump: major
  - task: deploy-uaa
    file: ci-resources/tasks/helm-install/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      COMPONENT: uaa
      HELM_CHART: uaa
      CLUSTER_NAME: ((cluster-name))
  - task: waiting-for-uaa
    attempts: 100
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/waiting-for-uaa/task.yml
  - put: ((cluster-name))-event-uaa-ready
    params:
      file: ((cluster-name))-event-uaa-ready/number
- name: deploy-scf-eirini
  plan:
  - get: eirini-source
    trigger: true
    passed:
    - create-docker-images
  - get: scf-resources
    trigger: true
  - get: ci-resources
  - get: state
  - get: eirini-release
  - get: ((cluster-name))-event-uaa-ready
    trigger: true
    passed: [deploy-scf-uaa]
  - task: deploy-scf
    file: ci-resources/tasks/helm-install/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      COMPONENT: scf
      HELM_CHART: cf
      CLUSTER_NAME: ((cluster-name))
  - task: smoke-eirini
    attempts: 100
    params:
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/eirini-smoke-tests/task.yml
- name: deploy-oratos
  plan:
  - get: ((cluster-name))-event-ready
    trigger: true
    passed:
    - create-docker-images
  - get: ci-resources
  - get: state
  - get: oratos
    trigger: true
  - task: deploy-oratos
    privileged: true
    file: ci-resources/tasks/deploy-oratos/task.yml
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
  - task: waiting-for-oratos
    attempts: 100
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/waiting-for-oratos/task.yml
- name: run-smoke-tests
  plan:
  - get: eirini-release
    passed: [deploy-scf-eirini]
    trigger: true
  - get: cf-smoke-tests
  - get: state
  - get: ci-resources
  - task: run smoke tests
    params:
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
    file: ci-resources/tasks/run-smoke-tests/task.yml
- name: run-cats-subset
  plan:
  - get: eirini-release
    passed: [run-smoke-tests]
    trigger: true
  - get: cats
  - get: state
  - get: ci-resources
  - task: run cats
    params:
      .: (( inject cats_conf ))
      IBMCLOUD_ACCOUNT: ((ibmcloud-account))
      IBMCLOUD_USER: ((ibmcloud-user))
      IBMCLOUD_PASSWORD: ((ibmcloud-password))
      CLUSTER_NAME: ((cluster-name))
      SKIPPED_TESTS: >
          Default Environment Variables
          | Buildpack cache
          | Crashing
          | Context Paths
          | Multiple App Ports
          | A running application
          | Buildpacks
          | loggregator
          | Environment Variables Groups
          | An application printing a bunch of output
          | Encoding
          | Logging
          | Application Lifecycle
          | Wildcard Routes
          | Getting instance information
          | Routing Transparency
    file: ci-resources/tasks/run-cats/task.yml

resources:
- name: eirini-source
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - src/code.cloudfoundry.org/eirini
- name: eirini-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
- name: scf-uaa-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - scf/helm/uaa
- name: scf-resources
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini-release.git
    branch: ((eirini-release-branch))
    paths:
    - scf/helm/cf
- name: ((cluster-name))-event-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ((cluster-name))-event-ready
    private_key: ((github-private-key))
- name: ((cluster-name))-event-uaa-ready
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: events
    file: ((cluster-name))-event-ready
    private_key: ((github-private-key))
- name: oratos
  type: git
  source:
    uri: https://github.com/gdankov/oratos-deployment
    branch: eirini
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: cats
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
