#!/bin/bash

readonly TARGET=$1


fly -t "$TARGET" set-pipeline -p fluentd \
  --config pipeline.yml \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)"
