---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diegoteam/eirini

inputs:
- name: ci-resources
- name: eirini

run:
  path: ci-resources/tasks/run-static-checks.sh
