#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly world_name=eirini-pr
readonly target="${1:-eirini}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"
readonly worker_count=${3:-"3"}
readonly diego_cell_count="3"
readonly rootfs_version="${4:-"v66.0.0"}"

aviator -f "$basedir"/aviator.yml

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var ci-resources-branch="new-ci-164492513" \
  --var eirini-release-branch="new-ci-164492513" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
  --var eirini-pr-webhook-token="$(pass eirini/github/eirini/webhook-token)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var diego-cell-count="$diego_cell_count" \
  --var worker_count="$worker_count" \
  --var storage_class="ibmc-block-gold" \
  --var enable_opi_staging=false \
  --var world-name="$world_name" \
  --var rootfs_version="$rootfs_version" \
  --load-vars-from "$private_repo/concourse/common.yml"
