#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly world_name=ci
readonly plain_yaml_gcp_cluster_name=monaco
readonly target="${1:-eirini}"
readonly working_branch=${3:-"master"}
readonly ci_branch=${4:-"master"}
export worker_count=${5:-"3"}

basedir="$(cd "$(dirname "$0")" && pwd)"
pushd "$basedir"
{
  aviator
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var world-name="$world_name" \
  --var gcp-cluster-name="$plain_yaml_gcp_cluster_name" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-zone="europe-west1-b" \
  --var gcp-region="europe-west1" \
  --var ci-resources-branch="$ci_branch" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var eirinifs-private-key="$(pass eirini/github/eirinifs/ssh-key)" \
  --var eirinifs-branch="master" \
  --var eirini-release-branch="develop" \
  --var eirini-branch="$working_branch" \
  --var cloud-controller-ng-branch="crds-main" \
  --var worker_count="$worker_count" \
  --var nats-password="$(pass eirini/ci/nats-password)" \
  --var wiremock-keystore-pass="$(pass eirini/ci/wiremock-keystore-password)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
