#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly world_name=ci
readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target=$1
readonly private_repo=$2
readonly worker_count=$3

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

aviator -f "$basedir"/aviator.yml

fly --target "$target" \
  set-pipeline \
    --config "$PIPELINE_YML" \
    --pipeline $world_name \
    --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
    --var ibmcloud-user=eirini@cloudfoundry.org \
    --var ibmcloud-password="$(pass show eirini/ibm-id)" \
    --var cluster-name=$world_name \
    --var ci-resources-branch="master" \
    --var dockerhub-user=eiriniuser \
    --var dockerhub-password="$(pass eirini/docker-hub)" \
    --var worker_count="$worker_count" \
    --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
    --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
    --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
    --var eirini-release-branch=develop \
    --load-vars-from "$private_repo/concourse/common.yml" \

fly --target "$target" \
    expose-pipeline \
    --pipeline $world_name
