#@ load("@ytt:data", "data")

#@ load("@ci:notifications.lib.yml", "notify_slack")
#@ load("@ci:resources.lib.yml", "resources")
#@ load("@ci:testing.lib.yml", "testing")
#@ load("@ci:ci_automation.lib.yml", "ci_automation")

groups:
- jobs:
  - check-shell
  - format-shell
  - check-golangci-linters
  name: checkers

jobs:
- name: check-shell
  on_failure: #@ notify_slack()
  plan:
  - get: ci-resources
    trigger: true
  - task: run-shellcheck
    config: #@ testing.run_shellcheck()
- name: format-shell
  on_failure: #@ notify_slack()
  plan:
  - get: ci-resources
    trigger: true
  - task: run-shfmt
    config: #@ testing.run_shfmt()
- name: check-golangci-linters
  on_failure: #@ notify_slack()
  plan:
  - get: golangci-lint-image
    trigger: true
  - get: eirini
    trigger: true
  - task: check-golangci-linters
    config: #@ ci_automation.check_golangci_linters()

resource_types:
- #@ resources.registry_image_type("slack-notification", "cfcommunity/slack-notification-resource")

resources:
- #@ resources.slack()
- #@ resources.git("eirini", "cloudfoundry/eirini")
- #@ resources.git("ci-resources", "cloudfoundry/eirini-ci")
- #@ resources.eirini_docker_image("golangci-lint")
