#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

basedir="$(cd "$(dirname "$0")" && pwd)"
readonly basedir
target="${1:-eirini}"
readonly target

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

pushd "$basedir"
{
  aviator
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline q-check \
  --var ci-resources-branch="master" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var eirini-branch="master" \
  --var eirini-release-branch="develop" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"

fly --target "$target" \
  expose-pipeline \
  --pipeline q-check
