#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

readonly target="${1:-eirini}"

basedir="$(cd "$(dirname "$0")" && pwd)"
pushd "$basedir"
{
  aviator
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline maintenance \
  --var gcp-service-account-json="$(pass eirini/gcp-ci-disk-deleter-json-key)" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
