#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

readonly target="${1:-eirini}"
readonly worker_count=${2:-"3"}
readonly dev_cluster_names=("lisbon" "barcelona")
pushd "$SCRIPT_DIR/../cf4k8s" || exit 1
{
  for name in "${dev_cluster_names[@]}"; do
    ./set-pipeline "$name" true "$worker_count" "$target"
  done
}
popd || exit 1
