#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

pipeline_yml=$(mktemp)
# shellcheck disable=SC2064
trap "rm $pipeline_yml" EXIT
readonly pipeline_yml
readonly target="${1:-eirini}"

ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
  --data-value="dockerhub.username=eiriniuser" \
  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
  --data-value="private_keys.eirinidotcf=$(pass eirini/github/eirinidotcf/ssh-key)" \
  --data-value="private_keys.eirini_private_config=$(pass eirini/github/private-config/ssh-key)" \
  --data-value="gcp.service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --data-value="postfacto.mysql.address=$(gcloud --project cff-eirini-peace-pods sql instances describe postfacto-cf4k8s4a8e --format="value(ipAddresses[0].ipAddress)")" \
  --data-value="postfacto.mysql.password=$(pass show eirini/postfacto-cf4k8s4a8e/mysql-admin-password)" \
  --data-value="jefe.github_oauth.client_id=$(pass eirini/jefe/client-id)" \
  --data-value="jefe.github_oauth.client_secret=$(pass eirini/jefe/client-secret)" \
  --data-value="jefe.db.password=$(pass eirini/jefe/dbuser-pass)" \
  --data-value="jefe.db.address=$(gcloud sql instances describe jefe-db --format="json" | jq -r '.ipAddresses[] | select(.type=="PRIVATE").ipAddress')" \
  --data-value="jefe.admin_password=$(pass eirini/jefe/admin-pass)" \
  --data-value="pairup.firebase_conf=$(pass eirini/pairup/conf.js)" \
  >"$pipeline_yml"

fly --target "$target" \
  set-pipeline \
  --config "$pipeline_yml" \
  --pipeline egg
