#!/bin/bash

set -euo pipefail

if [ "${1:-x}" == "help" ]; then
  cat <<EOF
  Usage:

        $ ./set-pipeline <CONCOURSE_TARGET> <PRIVATE_REPO>
EOF
  exit 0
fi

script_dir="$(cd "$(dirname "$0")" && pwd)"
private_repo=$(cd "$script_dir/../../../eirini-private-config" && pwd)
target="${1:-eirini}"

fly -t "${target}" \
  set-pipeline \
  -p check-dhall \
  -c <(dhall-fly <<<"$script_dir/pipeline.dhall") \
  --load-vars-from "$private_repo/concourse/common.yml"
