#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

readonly target="${1:-eirini}"
readonly worker_count=${2:-"3"}
readonly dev_cluster_names=("okinawa" "lisbon" "barcelona" "velikotarnovo")
pushd "$PROJECT_ROOT/pipelines/cf4k8s" || exit 1
{
  for name in "${dev_cluster_names[@]}"; do
    ./set-pipeline "$name" true "$worker_count" "$target"
  done
}
popd || exit 1
