#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

readonly target="${1:-eirini}"
readonly worker_count=${2:-"3"}
readonly dev_cluster_names=("okinawa" "lisbon" "barcelona" "velikotarnovo")
pushd "$PROJECT_ROOT/pipelines/cf4k8s" || exit 1
{
  for name in "${dev_cluster_names[@]}"; do
    PIPELINE_YML=$(mktemp)
    export PIPELINE_YML
    aviator

    fly --target "$target" \
      set-pipeline \
      --config "$PIPELINE_YML" \
      --pipeline "$name" \
      --var world-name="$name" \
      --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
      --var ibmcloud-user=eirini@cloudfoundry.org \
      --var ibmcloud-password="$(pass show eirini/ibm-id)" \
      --var ci-resources-branch="master" \
      --var eirini-release-branch="master" \
      --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
      --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
      --var eirini-staging-repo-key="$(pass eirini/github/eirini-staging/ssh-key)" \
      --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
      --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
      --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
      --var gcp-region="europe-west1" \
      --var gcp-zone="europe-west1-b" \
      --var gcp-dns-service-account-json="$(pass eirini/gcp-ci-dns-admin-json-key)" \
      --var worker_count="$worker_count" \
      --var slack-webhook="$(pass eirini/ci/slack-webhook)" \
      --var nats-password="$(pass eirini/ci/nats-password)" \
      --var cluster-admin-password="$(pass eirini/ci/cluster-admin-password)" \
      --var uaa-admin-client-secret="$(pass eirini/ci/uaa-admin-client-secret)"
  done
}
popd || exit 1
