#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly world_name=ci-new
readonly target="${1:-flintstone}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"
readonly worker_count=${3:-"1"}

aviator -f "$basedir"/aviator.yml

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var integration-test-cluster-name="$world_name-integration" \
  --var cluster-with-diego-staging-name="$world_name-integration" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var ci-resources-branch="master" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var eirini-release-branch=develop \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var worker_count="$worker_count" \
  --var enable_opi_staging=false \
  --load-vars-from "$private_repo/concourse/common.yml"
