#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly world_name=bump-go
readonly target="${1:-eirini}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"

dhall-fly <<<"$basedir/pipeline.dhall" >"$PIPELINE_YML"

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var ci-resources-branch="master" \
  --var eirini-release-branch="develop" \
  --var eirini-branch="bump-dependencies" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
  --var pr-webhook-token="$(pass eirini/github/eirini/webhook-token)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var gcs-json-key="$(pass eirini/gcs-json-key)" \
  --var worker_count="3" \
  --var storage_class="ibmc-block-gold" \
  --var world-name="$world_name" \
  --load-vars-from "$private_repo/concourse/common.yml"
