#@ load("@ytt:data", "data")

#@ load("@ci:notifications.lib.yml", "notify_slack")
#@ load("@ci:resources.lib.yml", "resources")

jobs:
- name: update-ci-image
  on_failure: #@ notify_slack()
  plan:
  - get: golang-image
    trigger: true
  - get: ci-image-source
    trigger: true
  - put: ci-image
    get_params:
      skip_download: true
    params:
      build: ci-image-source/images/ci

- name: update-gcloud-image
  on_failure: #@ notify_slack()
  plan:
  - get: gcloud-sdk
    trigger: true
  - get: gcloud-image-source
    trigger: true
  - put: gcloud-image
    get_params:
      skip_download: true
    params:
      build: gcloud-image-source/images/gcloud

- name: update-telepresence-image
  on_failure: #@ notify_slack()
  plan:
  - get: telepresence-image-source
    trigger: true
  - put: telepresence-image
    get_params:
      skip_download: true
    params:
      build: telepresence-image-source/images/telepresence

- name: update-golangci-lint-image
  on_failure: #@ notify_slack()
  plan:
  - get: golangci-lint
    trigger: true
  - get: golangci-lint-image-source
    trigger: true
  - put: golangci-lint-image
    get_params:
      skip_download: true
    params:
      build: golangci-lint-image-source/images/golangci-lint

resource_types:
- #@ resources.registry_image_type("slack-notification", "cfcommunity/slack-notification-resource")

resources:
- #@ resources.slack()

- #@ resources.docker_image("golang-image", "golang")
- #@ resources.eirini_docker_image("ci")

- #@ resources.docker_image("gcloud-sdk", "google/cloud-sdk")
- #@ resources.eirini_docker_image("gcloud")

- #@ resources.eirini_docker_image("golangci-lint")
- #@ resources.docker_image("golangci-lint", "golangci/golangci-lint")

- #@ resources.eirini_docker_image("telepresence")

#@ for image in ["ci", "gcloud", "golangci-lint", "telepresence"]:
- name: #@ image + "-image-source"
  type: git
  icon: git
  source:
    branch: master
    paths:
    - #@ "images/" + image + "/Dockerfile"
    uri: https://github.com/cloudfoundry/eirini-ci
#@ end
