#!/bin/bash

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
target="${1:-eirini}"

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

pushd "$script_dir"
{
  aviator
}
popd

fly -t "${target}" \
  set-pipeline \
  -p ci-images \
  -c "$PIPELINE_YML" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var ci-resources-branch="master" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"
