#!/bin/bash

if [ "$1" == "help" ]; then
  cat <<EOF
  Usage:

        $ ./set-pipeline <CONCOURSE_TARGET> <PRIVATE_REPO>
EOF
  exit 0
fi

export TARGET="${1?target not defined}"
export PRIVATE_REPO="${2?private repo not defined}"

DOCKER_HUB_PASSWORD="$(pass eirini/docker-hub)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR"/../.. && pwd)"
export DOCKER_HUB_PASSWORD
export SCRIPT_DIR
export PROJECT_ROOT

aviator -f "$SCRIPT_DIR"/aviator.yml
