#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

basedir="$(cd "$(dirname "$0")" && pwd)"
readonly basedir

world_name="${1:?}"
readonly world_name
enable_redeploy="${2:-false}"
readonly enable_redeploy
worker_count=${3:-"3"}
readonly worker_count
target="${4:-eirini}"
readonly target
windows_pool="${5:-false}"
readonly windows_pool

pushd "$basedir"
{
  redeploy_file_var=""
  recreate_file_var=""
  timer_resources_var=""
  if $enable_redeploy; then
    redeploy_file_var="- ./add-redeploy-cf-for-k8s-timer.yml"
    recreate_file_var="- ./add-cluster-recreate-timer.yml"
    timer_resources_var="- ../../modules/resources/timer-resources.yml"
  fi
  aviator \
    --var redeploy-trigger="$redeploy_file_var" \
    --var recreate-trigger="$recreate_file_var" \
    --var timer-resources="$timer_resources_var"
}
popd

if ! flightattendant -target "$target"; then
  echo "not logged in to concourse - attempting to log in"
  fly -t "$target" login --team-name main --concourse-url https://jetson.eirini.cf-app.com/
fi

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ci-resources-branch="master" \
  --var cluster-admin-password="$(pass eirini/ci/cluster-admin-password)" \
  --var eirini-release-branch="master" \
  --var gcp-region="europe-west1" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-zone="europe-west1-b" \
  --var github-access-token="$(pass eirini/github/eirinici/access-token)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)" \
  --var uaa-admin-client-secret="$(pass eirini/ci/uaa-admin-client-secret)" \
  --var worker_count="$worker_count" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var world-name="$world_name" \
  --var windows-pool="$windows_pool"
