#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

readonly excluded_pipelines=("cf4k8s/" "shared/" "fakes/")

pushd "$SCRIPT_DIR"
{
  for pipeline in */; do
    if [[ ! "${excluded_pipelines[@]}" =~ "$pipeline" ]]; then
      clear
      echo "+----------------------------------------------"
      echo "| Setting pipeline $pipeline"
      echo "+----------------------------------------------"

      $pipeline/set-pipeline
    fi
  done
}
popd
