#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

readonly main_pipelines=(acceptance ci check-shell ci-images dev-envs egg)
for pipeline in ${main_pipelines[@]}; do
  $PROJECT_ROOT/pipelines/$pipeline/set-pipeline
done
