groups:
- name: eirini-ci
  jobs:
  - (( append ))
  - run-static-checks

jobs:
- name: run-static-checks
  plan:
  - get: eirini
    trigger: true
    passed:
      - run-unit-tests
  - get: ci-resources
  - task: run-static-checks
    file: ci-resources/tasks/run-static-checks.yml

resources:
- name: eirini
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/eirini.git
    branch: ((eirini-branch))
