groups:
- name: eirini-cd
  jobs:
  - (( append ))
  - run-smoke-tests

resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/gdankov/cf-smoke-tests.git
    branch: eirini

jobs:
- name: run-smoke-tests
  plan:
  - get: ((world_name))-cf-deployment-events
    trigger: true
    passed:
    - set-iptable-rules
  - get: cf-smoke-tests
  - get: state
  - get: ci-resources
  - task: run smoke tests
    params:
      DIRECTOR_NAME: ((world_name))
      KUBE_CONF: ((kube_conf))
    file: ci-resources/tasks/run-smoke-tests.yml
