#@data/values
---
dockerhub:
  username:
  password:
gcp:
  service_account_json:
  zone: europe-west1-b
  region: europe-west1
  worker_count:
  machine_type: e2-custom-2-8192
private_keys:
  eirinici:
repo_branches:
  eirini_ci:
