#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

pipeline_yml=$(mktemp)
readonly pipeline_yml
# shellcheck disable=SC2064
trap "rm $pipeline_yml" EXIT

target="${1:-korifi}"
readonly target

worker_count=${2:-"3"}
readonly worker_count

working_branch=${3:-"master"}
readonly working_branch

ci_branch=${4:-"master"}
readonly ci_branch

if ! fly -t "$target" status &>/dev/null; then
  fly -t "$target" login
fi

# We want this script to exit with error if pass or gcloud fails rather than
# silently interpolating an empty string into the pipeline vars!
#
# Assigning the subshell stdout to a variable preserves the expected semantics
# of errexit, as these assignments are "simple commands" rather than
# substitutions.
#
# This is a giant gotcha with shell scripts!
# http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_01

dockerhub_password=$(pass eirini/docker-hub)
private_keys_eirinici=$(pass eirini/github/eirinici/ssh-key)
gcp_service_account_json=$(pass eirini/gcs-eirini-ci-terraform-json-key)
access_tokens_eirini_ci=$(pass eirini/github/eirinici/access-token)

ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
  --ignore-unknown-comments \
  --data-value="dockerhub.username=eiriniuser" \
  --data-value="dockerhub.password=$dockerhub_password" \
  --data-value="private_keys.eirinici=$private_keys_eirinici" \
  --data-value="gcp.service_account_json=$gcp_service_account_json" \
  --data-value="gcp.worker_count=$worker_count" \
  --data-value="repo_branches.eirini_controller=$working_branch" \
  --data-value="access_tokens.eirini_ci=$access_tokens_eirini_ci" \
  --data-value="repo_branches.eirini_ci=$ci_branch" \
  >"$pipeline_yml"

noColor=
if ! [ -t 1 ]; then
  noColor=--no-color
fi

fly --target "$target" \
  set-pipeline \
  "$noColor" \
  --config "$pipeline_yml" \
  --team zzz_eirini \
  --pipeline eirini-controller
