#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly target=$1
readonly world_name=$2
readonly private_repo=$3
readonly ci_branch=${4:-master}
readonly basedir="$(cd "$(dirname "$0")" && pwd)"

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

aviator -f "$basedir"/aviator.yml

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ci-resources-branch="$ci_branch" \
  --load-vars-from "$private_repo/concourse/common.yml"
