#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target="${1:-flintstone}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

aviator -f "$basedir"/aviator.yml

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline check-shell \
  --load-vars-from "$private_repo/concourse/common.yml"

fly --target "$target" \
  expose-pipeline \
  --pipeline check-shell
