#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target="${1:-eirini}"

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

pushd "$basedir"
{
  aviator
}
popd

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline check-shell \
  --var ci-resources-branch="master" \
  --var slack-webhook="$(pass eirini/ci/slack-webhook)"

fly --target "$target" \
  expose-pipeline \
  --pipeline check-shell
