#!/bin/bash

is-pod-ready() {
  declare -r namespace="${1:?Namespace not provided}"
  declare -r resource_name="${2:?Resource name not provided}"
  local ready
  local phase
  ready="$(kubectl get pods "$resource_name" --namespace "$namespace" --output json | jq '.status.conditions[] | select(.type == "ContainersReady") | .status')"
  phase="$(kubectl get pods "$resource_name" --namespace "$namespace" --output jsonpath='{.status.phase}')"
  [[ "$ready" == "True" && "$phase" == "Running" ]]
}

is-labeled-container-ready() {
  declare -r namespace="${1:?Namespace not provided}"
  declare -r label="${2:?Label not provided}"
  kubectl get pods --selector "$label" --namespace "$namespace" --output jsonpath='{.items[0].status.containerStatuses[0].ready}'
}
