#!/bin/bash

is-container-ready() {
  declare -r namespace="${1:?Namespace not provided}"
  declare -r resource_name="${2:?Resource name not provided}"
  kubectl get pods "$resource_name" --namespace "$namespace" --output jsonpath='{.status.containerStatuses[0].ready}'
}

is-labeled-container-ready() {
  declare -r namespace="${1:?Namespace not provided}"
  declare -r label="${2:?Label not provided}"
  kubectl get pods --selector "$label" --namespace "$namespace" --output jsonpath='{.items[0].status.containerStatuses[0].ready}'
}
