#!/bin/bash

set -euo pipefail

PIPELINE_YML=$(mktemp)
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT PIPELINE_YML

readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target="${1:-eirini}"
readonly private_repo="${2:-$PROJECT_ROOT/../eirini-private-config}"

export worker_count

dhall-fly <<<"$basedir/pipeline.dhall" >"$PIPELINE_YML"

fly -t "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "eirini-release" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var gcp-service-account-json="$(pass eirini/gcs-eirini-ci-terraform-json-key)" \
  --var gcp-dns-service-account-json="$(pass eirini/gcp-ci-dns-admin-json-key)" \
  --var grafana-admin-password="$(pass eirini/ci-envs/grafana)" \
  --var storage_class="ibmc-block-gold" \
  --load-vars-from "$private_repo/concourse/common.yml" \
  --check-creds
