#!/bin/bash

if [ "$1" == "help" ]; then
  cat <<EOF
  Usage:

        $ ./set-pipeline <CONCOURSE_TARGET> <PRIVATE_REPO>
EOF
  exit 0
fi

export TARGET="${1?target not defined}"
export PRIVATE_REPO="${2?private repo not defined}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR"/../.. && pwd)"
export SCRIPT_DIR
export PROJECT_ROOT

aviator -f "$SCRIPT_DIR"/aviator.yml

fly -t "$TARGET" set-pipeline \
  --config "$SCRIPT_DIR"/spruced.yml \
  --pipeline rebase-cc \
  --load-vars-from "$PRIVATE_REPO/concourse/common.yml" \
  --var github-private-key="$(pass eirini/github/capi-release/ssh-key)" \
  --var cc_ng_key="$(pass eirini/github/mnitchev/cloud_controller_ng/ssh-key)"
