#@ load("@ytt:data", "data")

#@ load("@ci:notifications.lib.yml", "notify_slack")
#@ load("@ci:resources.lib.yml", "resources")
#@ load("@ci:testing.lib.yml", "testing")
#@ load("@ci:ci_automation.lib.yml", "ci_automation")

groups:
- jobs:
  - check-shell
  - format-shell
  - check-wip-branches
  - check-golangci-linters
  name: checkers

jobs:
- name: check-shell
  on_failure: #@ notify_slack()
  plan:
  - get: ci-resources
    trigger: true
  - #@ testing.run_shellcheck()
- name: format-shell
  on_failure: #@ notify_slack()
  plan:
  - get: ci-resources
    trigger: true
  - #@ testing.run_shfmt()
- name: check-wip-branches
  on_failure: #@ notify_slack()
  plan:
  - get: every-morning
    trigger: true
  - #@ ci_automation.check_wip_branches()
- name: check-golangci-linters
  on_failure: #@ notify_slack()
  plan:
  - get: golangci-lint-image
    trigger: true
  - get: eirini
    trigger: true
  - #@ ci_automation.check_golangci_linters()

resource_types:
- #@ resources.registry_image_type("slack-notification", "cfcommunity/slack-notification-resource")

resources:
- #@ resources.slack()
- #@ resources.git("eirini", "cloudfoundry-incubator/eirini")
- #@ resources.git("ci-resources", "cloudfoundry-incubator/eirini-ci")
- #@ resources.slack()
- #@ resources.eirini_docker_image("golangci-lint")
- icon: alarm
  name: every-morning
  source:
    start: 5:00 AM
    stop: 6:00 AM
  type: time
