#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

pipeline_yml=$(mktemp)
# shellcheck disable=SC2064
trap "rm $pipeline_yml" EXIT
readonly pipeline_yml
readonly target="${1:-eirini}"

ytt -f "$SCRIPT_DIR" -f "$SCRIPT_DIR/../shared" \
  --data-value="slack.webhook=$(pass eirini/ci/slack-webhook)" \
  --data-value="dockerhub.username=eiriniuser" \
  --data-value="dockerhub.password=$(pass eirini/docker-hub)" \
  >"$pipeline_yml"

fly --target "$target" \
  set-pipeline \
  --config "$pipeline_yml" \
  --pipeline q-check
