#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if [[ "$#" -lt 4 ]]; then
  echo "Usage $0 <world_name> <target> <private_repo> <working_branch> [worker_count] [enable_opi_staging]" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly world_name=$1
readonly basedir="$(cd "$(dirname "$0")" && pwd)"
readonly target=$2
readonly private_repo=$3
readonly working_branch=$4
readonly worker_count=${5:-"1"}
readonly enable_opi_staging=${6:-""}

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

aviator -f "$basedir"/aviator.yml

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var world-name="$world_name" \
  --var ci-resources-branch="master" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var eirini-release-branch="$working_branch" \
  --var worker_count="$worker_count" \
  --var enable_opi_staging="${enable_opi_staging}" \
  --var capi-release-branch=develop \
  --load-vars-from "$private_repo/concourse/common.yml"
