#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if [[ "$#" -lt 1 ]]; then
  echo "Usage $0 <world_name> [<target>] [<private_repo>] [eirini_branch] [eirini_release_branch] [ci_branch] [worker_count] [storage_class]" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
export PROJECT_ROOT

readonly world_name=$1
readonly target="${2:-eirini}"
readonly private_repo="${3:-$PROJECT_ROOT/../eirini-private-config}"
readonly eirini_branch=${4:-"master"}
readonly eirini_release_branch=${5:-"develop"}
readonly ci_branch=${6:-"master"}
readonly worker_count=${7:-"3"}
readonly storage_class=${8:-"ibmc-block-gold"}
readonly basedir="$(cd "$(dirname "$0")" && pwd)"

PIPELINE_YML=$(mktemp)
export PIPELINE_YML

dhall-to-json <<< "$basedir/pipeline.dhall $worker_count" \
  | jq '.resources = (.resources|unique)' \
  | jq '.resource_types = (.resource_types|unique)' \
  | jq '.groups = (.groups | group_by(.name) | map({name: .[0].name, jobs: (map(.jobs) | flatten) }))' > "$PIPELINE_YML"

fly --target "$target" \
  set-pipeline \
  --config "$PIPELINE_YML" \
  --pipeline "$world_name" \
  --var ibmcloud-account=7e51fbb83371a0cb0fd553fab15aebf4 \
  --var ibmcloud-user=eirini@cloudfoundry.org \
  --var ibmcloud-password="$(pass show eirini/ibm-id)" \
  --var world-name="$world_name" \
  --var ci-resources-branch="$ci_branch" \
  --var dockerhub-user=eiriniuser \
  --var dockerhub-password="$(pass eirini/docker-hub)" \
  --var github-private-key="$(pass eirini/github/private-config/ssh-key)" \
  --var eirini-repo-key="$(pass eirini/github/eirini/ssh-key)" \
  --var eirini-release-repo-key="$(pass eirini/github/eirini-release/ssh-key)" \
  --var gcs-json-key="$(pass eirini/gcs-json-key)" \
  --var eirini-release-branch="$eirini_release_branch" \
  --var eirini-branch="$eirini_branch" \
  --var worker_count="$worker_count" \
  --var storage_class="$storage_class" \
  --load-vars-from "$private_repo/concourse/common.yml"
